feature: Hook for checking cache status
CagriAldemir/react-cache-buster pull request #18
Opened 2023-03-04 00:10 UTC by MartinCura

Closes #17 

This PR makes CacheBuster into a Provider with a Context so that any distant child component can call `checkCacheStatus()` without needing the user to reload the page, effectively allowing them to maybe bust the cache whenever they want.

Other small changes, which can be removed if you want:
* add `@ts-check to top of file, so IDE tells on type erros without completely switching to TS
* remove arg from `window.location.reload()` as it was a type error (it has no arguments: https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-location-reload)
* wrap `checkCacheStatus` in an `useCallback`
* updated `caniuse` in lockfile

Example usage of new hook:

```jsx
// ...
import { useLocation } from 'react-router-dom';
import CacheBuster, { useCacheBuster } from 'react-cache-buster';

const isEnabled = process.NODE_ENV === 'production';

const AppUpdater = ({ children }: { children: ReactNode }) => {
    const VersionChecker = ({ children }: { children: ReactNode }) => {
        const [skippedFirstRender, setSkippedFirstRender] =
            useState<boolean>(false);
        const location = useLocation();
        const { checkCacheStatus } = useCacheBuster();

        useEffect(() => {
            if (!isEnabled) {
                return;
            }
            if (!skippedFirstRender) {
                setSkippedFirstRender(true);
                return;
            }
            checkCacheStatus();
        }, [location, checkCacheStatus]);

        return <>{children}</>;
    };

    return (
        <CacheBuster
            currentVersion={packageInfo.version}
            isEnabled={isEnabled}
            isVerboseMode={false}
            loadingComponent={<p style={{ margin: '20px' }}>Loading app...</p>}
            // really make sure browser doesn't cache meta.json
            metaFileDirectory={`/meta.json?t=${Date.now()}#`}
        >
            <VersionChecker>{children}</VersionChecker>
        </CacheBuster>
    );
};
```

2023-03-05 14:54 UTC, MartinCura commented
Added new `reloadOnDowngrade` prop.

2023-03-06 05:36 UTC, CagriAldemir commented
Hi @MartinCura. Thank you for your development. I think it's a good idea too. I will review and publish the new version this week.

2023-03-07 21:16 UTC, robmadden commented
Hi there, thanks for creating this library.

I know it's only been one day, but is there any chance you could release this feature? I was hoping to use this library in one of my projects, thanks!

2023-03-08 03:50 UTC, CagriAldemir commented on README.md
> +      {/* // Your actual root component... */}
Can you revert this comment line to `// Your actual root component...`

2023-03-08 03:53 UTC, CagriAldemir commented on README.md
> +| reloadOnDowngrade | Boolean  | :x:                | Whether to also bust the cache and reload if the version fetched from the server is lower.
Can you add `Default: **false**` to end of description?

2023-03-08 03:59 UTC, CagriAldemir commented on src/CacheBuster.js
> +        window.location.reload();
The "forceRefresh" parameter is still [supported by the Firefox browser](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload#parameters). So you better add the parameter again.

2023-03-08 04:09 UTC, CagriAldemir requested changes
I added some comments. Can you check them?

You also added a hook. Thank you for that. However, I would be very happy if you add the details about this hook to the README file and add a simple example of its use in the example project located in [this directory](https://github.com/CagriAldemir/react-cache-buster/tree/master/example).

2023-03-08 12:07 UTC, MartinCura commented on src/CacheBuster.js
> +        window.location.reload();
Missed that! Thanks for pointing it out.

2023-03-08 12:09 UTC, MartinCura commented
There you go, @CagriAldemir. Happy to change anything else as you wish, but also feel free to fix any nits yourself (i think you should be able to push to my branch) 😃 

We're already using this so very happy if we can merge it soon.

2023-03-08 20:39 UTC, robmadden commented
Thanks for your efforts!

2023-03-13 13:57 UTC, robmadden commented
Friendly ping: any update here?

2023-03-16 14:28 UTC, MartinCura commented
> I added some comments. Can you check them?
> 
> You also added a hook. Thank you for that. However, I would be very happy if you add the details about this hook to the README file and add a simple example of its use in the example project located in [this directory](https://github.com/CagriAldemir/react-cache-buster/tree/master/example).

One more gentle ping, sorry 😄 I made the small changes you asked for. Is there anything else i can do to get this merged? 😇 Thank you.

2023-03-21 14:10 UTC, robmadden commented
👋  any update here?

2023-03-22 07:34 UTC, CagriAldemir approved these changes

2023-03-22 07:35 UTC, merged

2023-03-22 08:00 UTC, CagriAldemir commented
@MartinCura @robmadden Hello there. I could not review due to my workload, but I have just published the new version of Cache Buster. Thanks for support.

2023-03-22 12:51 UTC, robmadden commented
@CagriAldemir no worries, thanks for following up!

2023-03-22 17:20 UTC, MartinCura commented
No worries, thank you so much ! Already updating this dep in our repo.