On cache clear
CagriAldemir/react-cache-buster pull request #4
Opened 2021-12-10 11:15 UTC by Squair

This should satisfy #2

2021-12-10 21:44 UTC, CagriAldemir commented on package.json
> -  "version": "0.1.5",
Can u remove version increment line? Because I'm gonna add one more feature with this PR.

2021-12-10 21:45 UTC, CagriAldemir requested changes
Thank you for your support @Squair. I would be happy if you check my review comment.

2021-12-10 22:39 UTC, closed without merging

2021-12-10 22:52 UTC, Squair commented
@CagriAldemir Just noticed you made these changes yourself in master, just thought I'd double check - if you call onCacheClear before calling refreshCacheAndReload and it throws, wouldn't this give unpredictable results in the consuming code?

2021-12-10 22:59 UTC, CagriAldemir commented
Actually, you're right. However, if I call the function later, the page will already be refreshed this time. Maybe it would be more correct to use the "onCacheClear" function as follows. What do you say?

```javascript
  const refreshCacheAndReload = async () => {
    try {
      if (window?.caches) {
        const { caches } = window;
        const cacheNames = await caches.keys();
        for (const cacheName of cacheNames) {
          caches.delete(cacheName);
        }
        log('The cache has been deleted.');
        onCacheClear && onCacheClear();
        window.location.reload(true);
      }
    } catch (error) {
      log('An error occurred while deleting the cache.', true);
      log(error, true);
    }
  };
```

2021-12-10 23:19 UTC, Squair commented
@CagriAldemir It's better, but now I'm thinking about it, I'm not so sure about the practically of it. I don't think it's possible without getting a bit hacky, but it'd be really nice to be able to run onCacheClear after reloading the window, this way when someone hits an application you'd have a way to determine that the cache had to be cleared. This could then be used to notify them that new features were available or something like that - still possible before reloading I suppose, but a little more limiting

2021-12-16 20:58 UTC, CagriAldemir commented
> @CagriAldemir It's better, but now I'm thinking about it, I'm not so sure about the practically of it. I don't think it's possible without getting a bit hacky, but it'd be really nice to be able to run onCacheClear after reloading the window, this way when someone hits an application you'd have a way to determine that the cache had to be cleared. This could then be used to notify them that new features were available or something like that - still possible before reloading I suppose, but a little more limiting

I agree with you. But to implement your idea, we have to store a flag in local storage or session storage. What do u think about it?

2021-12-16 21:40 UTC, Squair commented
Yeah that could work - local storage feels like the best place. Happy to review a PR if you want a second pair of eyes 👍